# Generated by Django 4.1.7 on 2023-02-23 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("artist", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="")),
                ("audio_link", models.CharField(blank=True, max_length=200, null=True)),
                ("duration", models.CharField(max_length=20)),
                ("vote", models.SmallIntegerField(choices=[(0, "0")], default=0)),
                ("vote_prev", models.SmallIntegerField(default=0)),
                ("place", models.SmallIntegerField(default=0)),
                ("status", models.TextField(default="Nowość", max_length=20)),
                (
                    "data_list",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 2, 23, 20, 7, 53, 240623)
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.TextField(default="", max_length=15)),
                (
                    "song_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="songs.song"
                    ),
                ),
            ],
        ),
    ]
