# Generated by Django 3.2.5 on 2023-02-24 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='data_list',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 7, 30, 23, 44103)),
        ),
        migrations.AlterField(
            model_name='song',
            name='vote',
            field=models.SmallIntegerField(choices=[(0, '0')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='vote_prev',
            field=models.SmallIntegerField(),
        ),
    ]
